<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.30" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.12" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.30" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FunEvents.Application\FunEvents.Application.csproj" />
    <ProjectReference Include="..\FunEvents.Domain\FunEvents.Domain.csproj" />
    <ProjectReference Include="..\FunEvents.Infrastructure.Sql\FunEvents.Infrastructure.Sql.csproj" />
    <ProjectReference Include="..\FunEvents.Logging\FunEvents.Logging.csproj" />
  </ItemGroup>

</Project>
